[workspace]

members = [
    "data-model",
    "encoding",
    "fuzz",
    "lcmux",
    "meadowcap",
    "wgps",
    "store_simple_sled",
    "willow_25"
]
resolver = "2"

[workspace.lints.clippy]
type_complexity = "allow"
