[workspace]

members = ["data-model", "earthstar", "encoding", "fuzz", "lcmux", "meadowcap", "ufotofu_codec", "wgps", "wb_async_utils"]
resolver = "2"

[workspace.lints.clippy]
type_complexity = "allow"
