[package]
name = "willow-sideload"
version = "0.1.0"
edition = "2021"

[dependencies]
ufotofu_codec = { version = "0.1.1" }
willow-data-model = { path = "../data-model", version = "0.2.0" }

[lints]
workspace = true
